## 必要なライブラリを読み込む

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

## データ読み込み

In [2]:
! wc -l test.csv train.csv

 4577465 test.csv
 40428968 train.csv
 45006433 total

## データ用が多いので、絞って読み込み

In [3]:
train_fname = 'train.csv'
reader = pd.read_csv(train_fname, chunksize=1000)

In [4]:
df_train = reader.get_chunk(1000)

In [5]:
df_train.shape

(1000, 24)

In [6]:
df_train.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

In [7]:
df_train.columns

Index(['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

## データの欠損値、型、columnsを確認

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
id                  1000 non-null uint64
click               1000 non-null int64
hour                1000 non-null int64
C1                  1000 non-null int64
banner_pos          1000 non-null int64
site_id             1000 non-null object
site_domain         1000 non-null object
site_category       1000 non-null object
app_id              1000 non-null object
app_domain          1000 non-null object
app_category        1000 non-null object
device_id           1000 non-null object
device_ip           1000 non-null object
device_model        1000 non-null object
device_type         1000 non-null int64
device_conn_type    1000 non-null int64
C14                 1000 non-null int64
C15                 1000 non-null int64
C16                 1000 non-null int64
C17                 1000 non-null int64
C18                 1000 non-null int64
C19                 1000 non-null int64
C20                 1000 non-null int64
C21                 1000 non-null int64
dtypes: int64(14), object(9), uint64(1)
memory usage: 187.6+ KB

## Numericalデータの統計情報

In [9]:
df_train.describe()

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,1.000000e+03,1000.000000,1000.0,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,9.402135e+18,0.160000,14102100.0,1005.019000,0.185000,1.04700,0.178000,17716.240000,318.368000,56.488000,1968.148000,0.789000,124.672000,37637.883000,88.556000
std,2.390389e+18,0.366789,0.0,1.033299,0.388492,0.55054,0.605543,3115.731031,9.998227,35.787632,380.270482,1.227186,232.189622,48512.364147,46.087253
min,1.004777e+16,0.000000,14102100.0,1001.000000,0.000000,0.00000,0.000000,377.000000,216.000000,36.000000,112.000000,0.000000,35.000000,-1.000000,13.000000
25%,1.002866e+19,0.000000,14102100.0,1005.000000,0.000000,1.00000,0.000000,15705.000000,320.000000,50.000000,1722.000000,0.000000,35.000000,-1.000000,61.000000
50%,1.006611e+19,0.000000,14102100.0,1005.000000,0.000000,1.00000,0.000000,17653.000000,320.000000,50.000000,1974.000000,0.000000,35.000000,-1.000000,79.000000
75%,1.010323e+19,0.000000,14102100.0,1005.000000,0.000000,1.00000,0.000000,20362.000000,320.000000,50.000000,2277.000000,2.000000,39.000000,100084.000000,156.000000
max,1.014356e+19,1.000000,14102100.0,1010.000000,1.000000,5.00000,3.000000,21692.000000,320.000000,250.000000,2497.000000,3.000000,1835.000000,100233.000000,157.000000

## Categoricalデータの統計情報

In [10]:
df_train.describe(include=['O'])

,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model
count,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,122,109,10,75,15,7,127,910,341
top,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,0489ce3f,8a4875bd
freq,341,341,373,790,826,796,870,6,73

## hour列から　月、日、曜日、時を抜き出すために関数を用意

In [11]:
from datetime import datetime as dt
# hour列から　月、日、曜日、時を抜き出すために関数を用意

def get_month_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.month
def get_day_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.day
def get_weekday_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.weekday()
def get_hour_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.hour

In [12]:
def preprocess(df_train):
    
    # 上記で作成した関数をapplyで一括適用
    df_train["hour_month"] = df_train["hour"].apply(get_month_from_time)
    df_train["hour_day"] = df_train["hour"].apply(get_day_from_time)
    df_train["hour_weekday"] = df_train["hour"].apply(get_weekday_from_time)
    df_train["hour_hour"] = df_train["hour"].apply(get_hour_from_time)
   
    # カテゴリ変数からダミー変数の作成
    X = df_train.iloc[:, 0:28]
    colnames_categorical = ['site_id', 'site_domain','site_category', 'app_id', 'app_domain', 'app_category', 'device_id','device_ip', 'device_model']
#    X_dummy = pd.get_dummies(X[colnames_categorical])
#   X = pd.merge(X, X_dummy, left_index=True, right_index=True)
    X = X.drop(colnames_categorical, axis=1)
    
    
    return X

In [13]:
X = preprocess(df_train)

In [14]:
X

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21,hour_month,hour_day,hour_weekday,hour_hour
0,1000009418151094273,0,14102100,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
1,10000169349117863715,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
2,10000371904215119486,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
3,10000640724480838376,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,100084,79,10,21,1,0
4,10000679056417042096,0,14102100,1005,1,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0
5,10000720757801103869,0,14102100,1005,0,1,0,16920,320,50,1899,0,431,100077,117,10,21,1,0
6,10000724729988544911,0,14102100,1005,0,1,0,20362,320,50,2333,0,39,-1,157,10,21,1,0
7,10000918755742328737,0,14102100,1005,1,1,0,20632,320,50,2374,3,39,-1,23,10,21,1,0
8,10000949271186029916,1,14102100,1005,0,1,2,15707,320,50,1722,0,35,-1,79,10,21,1,0
9,10001264480619467364,0,14102100,1002,0,0,0,21689,320,50,2496,3,167,100191,23,10,21,1,0
10,10001868339616595934,0,14102100,1005,1,1,0,17747,320,50,1974,2,39,100019,33,10,21,1,0
11,10001966791793526909,0,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0
12,10002028568167339219,0,14102100,1005,0,1,2,20596,320,50,2161,0,35,100148,157,10,21,1,0
13,10002044883120869786,0,14102100,1005,0,1,0,19771,320,50,2227,0,687,100077,48,10,21,1,0
14,10002518649031436658,0,14102100,1005,0,1,0,20984,320,50,2371,0,551,-1,46,10,21,1,0
15,10003539039235338011,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,100084,79,10,21,1,0
16,10003585669470236873,0,14102100,1005,0,1,0,17914,320,50,2043,2,39,-1,32,10,21,1,0
17,10004105575081229495,0,14102100,1005,0,1,2,15708,320,50,1722,0,35,100084,79,10,21,1,0
18,10004181428767727519,0,14102100,1005,1,1,0,6558,320,50,571,2,39,-1,32,10,21,1,0
19,10004482643316086592,0,14102100,1005,0,1,0,21234,320,50,2434,3,163,100088,61,10,21,1,0
20,10004510652136496837,0,14102100,1005,0,1,0,20352,320,50,2333,0,39,-1,157,10,21,1,0
21,10004574413841529209,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
22,10004670021948955159,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
23,10004765361151096125,1,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0
24,10005249248600843539,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,100083,79,10,21,1,0
25,10005334911727438633,0,14102100,1010,1,4,0,21665,320,50,2493,3,35,-1,117,10,21,1,0
26,10005541670676403131,0,14102100,1005,1,1,0,20984,320,50,2371,0,551,100217,46,10,21,1,0
27,10005609489911213467,1,14102100,1005,0,1,0,21611,320,50,2480,3,297,100111,61,10,21,1,0
28,10005649443863261125,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
29,10005951398749600249,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,10139644451794942635,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
971,10139697731479064434,0,14102100,1005,0,1,0,16920,320,50,1899,0,431,100081,117,10,21,1,0
972,10139707365278316657,1,14102100,1005,1,1,0,17753,320,50,1993,2,1063,-1,33,10,21,1,0
973,10139970425612444870,0,14102100,1005,0,1,0,15705,320,50,1722,0,35,-1,79,10,21,1,0
974,10140055560798767842,0,14102100,1005,0,1,0,21611,320,50,2480,3,297,100111,61,10,21,1,0
975,10140137178498985581,0,14102100,1005,0,1,0,17239,320,50,1973,3,39,100119,23,10,21,1,0
976,10140638728626459396,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,-1,79,10,21,1,0
977,10140873544956365957,0,14102100,1005,1,1,0,20596,320,50,2161,0,35,-1,157,10,21,1,0
978,1014087862830005717,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,-1,79,10,21,1,0
979,10141326312159899433,1,14102100,1005,1,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
980,101413338699048894,0,14102100,1005,0,1,0,17239,320,50,1973,3,39,-1,23,10,21,1,0
981,10141388967817423817,0,14102100,1005,0,1,0,17875,320,50,2036,3,47,-1,156,10,21,1,0
982,10141666039360970473,0,14102100,1005,0,1,0,15705,320,50,1722,0,35,100084,79,10,21,1,0
983,10141793556467368079,0,14102100,1005,0,1,0,20362,320,50,2333,0,39,-1,157,10,21,1,0
984,10142100424706117380,1,14102100,1005,0,1,0,15704,320,50,1722,0,35,-1,79,10,21,1,0
985,10142317363215454853,0,14102100,1005,1,1,0,20363,216,36,2333,0,39,100077,157,10,21,1,0
986,10142552828948433405,0,14102100,1005,0,1,0,20969,320,50,2372,0,813,-1,46,10,21,1,0
987,10142669815216941825,1,14102100,1005,0,1,0,20362,320,50,2333,0,39,-1,157,10,21,1,0
988,1014268582257376890,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,-1,79,10,21,1,0
989,10142695155391256175,0,14102100,1005,0,1,0,20362,320,50,2333,0,39,-1,157,10,21,1,0
990,10142733630077293241,0,14102100,1005,0,1,0,15705,320,50,1722,0,35,-1,79,10,21,1,0
991,10142766708196242341,0,14102100,1005,0,1,0,20596,320,50,2161,0,35,-1,157,10,21,1,0
992,10142772622076486801,0,14102100,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
993,10142858394537559031,0,14102100,1005,0,1,0,6393,320,50,547,3,47,100084,23,10,21,1,0
994,10142948999679347601,0,14102100,1005,0,1,2,21611,320,50,2480,3,297,100111,61,10,21,1,0
995,10143043261436144411,0,14102100,1005,0,1,0,15708,320,50,1722,0,35,100084,79,10,21,1,0
996,1014322937494547310,0,14102100,1005,0,1,0,20596,320,50,2161,0,35,-1,157,10,21,1,0
997,10143295888139735045,0,14102100,1005,0,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0
998,10143417277678185860,0,14102100,1005,0,1,0,15703,320,50,1722,0,35,-1,79,10,21,1,0
999,10143559787734827068,1,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0

## ターゲット変数と特徴量を指定してsklearnに渡せるように準備する

In [15]:
target_col = 'click'
exclude_cols = ['click', 'id', 'hour']
feature_cols = [col for col in X.columns if col not in exclude_cols]

In [16]:
feature_cols

['C1',
 'banner_pos',
 'device_type',
 'device_conn_type',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'hour_month',
 'hour_day',
 'hour_weekday',
 'hour_hour']

## 説明変数（特徴量）

In [17]:
X[feature_cols].head()

,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21,hour_month,hour_day,hour_weekday,hour_hour
0,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
1,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
2,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
3,1005,0,1,0,15706,320,50,1722,0,35,100084,79,10,21,1,0
4,1005,1,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0

## 被説明変数（ターゲット変数）

In [18]:
X[target_col].head()

0    0
1    0
2    0
3    0
4    0
Name: click, dtype: int64

In [19]:
y = np.array(X[target_col])
X = np.array(X[feature_cols])

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [21]:
X

array([[1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       ...,
       [1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0]])

# モデルの作成

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

In [23]:
X_train, X_test, y_train, y_test = \
 train_test_split(X, y, test_size=0.3, random_state=1234)

In [24]:
X_train1, X_train2, y_train1, y_train2 = \
 train_test_split(X_train, y_train, test_size=0.3, random_state=1234)

## ランダムフォレスト

In [25]:
rf = RandomForestRegressor(random_state=1234)
rf.fit(X_train1, y_train1)
y_pred2 = rf.predict(X_train2)
rf_mse = mean_squared_error(y_train2, y_pred2)
print('Random Forest RMSE: ', np.sqrt(rf_mse))

Random Forest RMSE:  0.3598260350607517

In [26]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

181

## 変数増加法で変数選択をしてみる

In [27]:
def get_gfs_feature_indices(X, y, features, clf):
    X_train_, X_test_, y_train_, y_test_ = \
        train_test_split(X, y, test_size=0.3, random_state=1234)
    
    #どの特徴量が何列目にあるかを辞書型で保持
    feature_indices = {feature: idx for idx, feature in enumerate(features)}
   
    # 特徴量をユニークにする
    features = set(features)
    
    # 評価（MSE）の初期化
    last_mse = np.inf
    
    #選ばれた特徴量を保存するための空集合を用意
    chosen_features = set()

    while len(chosen_features) < len(features):
        mse_features = []
        
        # 集合は引き算すると差集合
        for feature in (features - chosen_features):
            candidates = chosen_features.union(set([feature]))
            indices = [feature_indices[feature] for feature in candidates]
            clf.fit(X_train_[:, indices], y_train_)
            y_pred = clf.predict(X_test_[:, indices])
            mse = mean_squared_error(y_test_, y_pred)
            mse_features += [(mse, feature)]
        mse, feature = min(mse_features, key= lambda x:x[0])
        
        if mse >= last_mse:
            break
        last_mse = mse
        print('Newly Added Feature: {},\tRMSE Score: {}'.format(feature, np.sqrt(mse)))
        chosen_features.add(feature)
    return [feature_indices[feature] for feature in chosen_features]

In [28]:
selected_feature_index = \
get_gfs_feature_indices(X=X_train, 
                        y=y_train, 
                        features=feature_cols, 
                        clf=RandomForestRegressor(random_state=1234))

Newly Added Feature: C21,	RMSE Score: 0.32586335381661247
Newly Added Feature: banner_pos,	RMSE Score: 0.3220932030332173
Newly Added Feature: hour_month,	RMSE Score: 0.3208797459235834

## 変数選択後の精度を確認

In [29]:
rf = RandomForestRegressor(random_state=1234)
rf.fit(X_train1[:, selected_feature_index], y_train1)
y_pred2 = rf.predict(X_train2[:, selected_feature_index])
rf_mse = mean_squared_error(y_train2, y_pred2)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.3208797459235834

In [30]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

185

In [31]:
rf = RandomForestRegressor(random_state=1234)

In [32]:
params = {'n_estimators': [10, 50, 100], 'max_depth': [5, 10, 50]}

In [33]:
import sklearn 
sklearn.__version__

'0.19.1'

In [34]:
#注意: scikit-learnのバージョンが、0.18の場合は、scoring='neg_mean_squared_error'とします
gscv = GridSearchCV(rf, param_grid=params, verbose=1,
                     cv=3, scoring='neg_mean_squared_error')

In [35]:
gscv.fit(X_train1[:, selected_feature_index], y_train1)

Fitting 3 folds for each of 9 candidates, totalling 27 fits

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    1.4s finished

GridSearchCV(cv=3, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=1234, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [10, 50, 100], 'max_depth': [5, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring='neg_mean_squared_error', verbose=1)

In [36]:
gscv.best_params_

{'max_depth': 5, 'n_estimators': 10}

## パラメーターチューニング後のスコア

In [37]:
rf = RandomForestRegressor(n_estimators=5, max_depth=5, random_state=1234)
rf.fit(X_train1[:, selected_feature_index ], y_train1)
y_pred2 = rf.predict(X_train2[:, selected_feature_index])
rf_mse = mean_squared_error(y_train2, y_pred2)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.32400667566265756

In [38]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

184

## テストデータへ適用して精度を確認する

In [39]:
rf = RandomForestRegressor(n_estimators=100, max_depth=50, random_state=1234)
rf.fit(X_train[:, selected_feature_index], y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=50,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=1234, verbose=0, warm_start=False)

In [40]:
y_pred_on_test = rf.predict(X_test[:, selected_feature_index])
rf_mse = mean_squared_error(y_test, y_pred_on_test)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.38777493932632634

In [41]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

184

## submission用csvの作成

In [42]:
test_fname = 'test.csv'
reader_test = pd.read_csv(test_fname, chunksize=1000)
df_test_origin = reader_test.get_chunk(1000)

In [43]:
df_test = preprocess(df_test_origin)

In [44]:
selected_feature_index2 = [
'C21',
'banner_pos',
'hour_month'
]

In [45]:
submit_data =  pd.Series(rf.predict(df_test[selected_feature_index2]), name='click', index=df_test_origin['id'])
submit_data.to_csv('submit_Quantitative_variable_1000.csv', header=True)