- ランダムフォレスト
- データ数　train.csv100000
- test.csv 100000

In [99]:
kensu = 100000
kensu_str = '100000'
submit_csv_name = 'submit_Quantitative_variable_' + kensu_str + '.csv'

## 必要なライブラリを読み込む

In [100]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

## データ用が多いので、絞って読み込み

In [101]:
train_fname = 'train.csv'
reader = pd.read_csv(train_fname, chunksize=kensu)

In [102]:
df_train = reader.get_chunk(kensu)

In [103]:
df_train.shape

(100000, 24)

In [104]:
df_train.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

In [105]:
df_train.columns

Index(['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

## データの欠損値、型、columnsを確認

In [106]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
id                  100000 non-null float64
click               100000 non-null int64
hour                100000 non-null int64
C1                  100000 non-null int64
banner_pos          100000 non-null int64
site_id             100000 non-null object
site_domain         100000 non-null object
site_category       100000 non-null object
app_id              100000 non-null object
app_domain          100000 non-null object
app_category        100000 non-null object
device_id           100000 non-null object
device_ip           100000 non-null object
device_model        100000 non-null object
device_type         100000 non-null int64
device_conn_type    100000 non-null int64
C14                 100000 non-null int64
C15                 100000 non-null int64
C16                 100000 non-null int64
C17                 100000 non-null int64
C18                 100000 non-null int64
C19                 100000 non-null int64
C20                 100000 non-null int64
C21                 100000 non-null int64
dtypes: float64(1), int64(14), object(9)
memory usage: 18.3+ MB

## Numericalデータの統計情報

In [107]:
df_train.describe()

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,1.000000e+05,100000.000000,100000.0,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,9.500813e+18,0.174900,14102100.0,1005.034410,0.19830,1.055730,0.199270,17682.145900,318.333960,56.818920,1964.034380,0.789350,131.734480,37874.227610,88.555670
std,5.669410e+18,0.379883,0.0,1.088741,0.40264,0.583993,0.635268,3237.735265,11.931939,36.924104,394.962696,1.223761,244.076787,48546.274316,45.482841
min,3.237563e+13,0.000000,14102100.0,1001.000000,0.00000,0.000000,0.000000,375.000000,120.000000,20.000000,112.000000,0.000000,33.000000,-1.000000,13.000000
25%,4.183340e+18,0.000000,14102100.0,1005.000000,0.00000,1.000000,0.000000,15704.000000,320.000000,50.000000,1722.000000,0.000000,35.000000,-1.000000,61.000000
50%,1.074496e+19,0.000000,14102100.0,1005.000000,0.00000,1.000000,0.000000,17654.000000,320.000000,50.000000,1993.000000,0.000000,35.000000,-1.000000,79.000000
75%,1.457542e+19,0.000000,14102100.0,1005.000000,0.00000,1.000000,0.000000,20362.000000,320.000000,50.000000,2306.000000,2.000000,39.000000,100083.000000,156.000000
max,1.844670e+19,1.000000,14102100.0,1010.000000,5.00000,5.000000,5.000000,21705.000000,728.000000,480.000000,2497.000000,3.000000,1835.000000,100248.000000,157.000000

## Categoricalデータの統計情報

In [108]:
df_train.describe(include=['O'])

,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model
count,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,893,780,16,704,55,19,7202,40376,2473
top,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,6b9769f2,8a4875bd
freq,35051,35051,37696,78227,82886,78828,86935,838,6886

## hour列から　月、日、曜日、時を抜き出すために関数を用意

In [109]:
from datetime import datetime as dt
# hour列から　月、日、曜日、時を抜き出すために関数を用意

def get_month_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.month
def get_day_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.day
def get_weekday_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.weekday()
def get_hour_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.hour

In [110]:
def preprocess(df_train):
    
    # 上記で作成した関数をapplyで一括適用
    df_train["hour_month"] = df_train["hour"].apply(get_month_from_time)
    df_train["hour_day"] = df_train["hour"].apply(get_day_from_time)
    df_train["hour_weekday"] = df_train["hour"].apply(get_weekday_from_time)
    df_train["hour_hour"] = df_train["hour"].apply(get_hour_from_time)
   
    # カテゴリ変数からダミー変数の作成
    X = df_train.iloc[:, 0:28]
    colnames_categorical = ['site_id', 'site_domain','site_category', 'app_id', 'app_domain', 'app_category', 'device_id','device_ip', 'device_model']
#    X_dummy = pd.get_dummies(X[colnames_categorical])
#   X = pd.merge(X, X_dummy, left_index=True, right_index=True)
    X = X.drop(colnames_categorical, axis=1)
    
    
    return X

In [111]:
X = preprocess(df_train)

In [112]:
X

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21,hour_month,hour_day,hour_weekday,hour_hour
0,1.000009e+18,0,14102100,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
1,1.000017e+19,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
2,1.000037e+19,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
3,1.000064e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,100084,79,10,21,1,0
4,1.000068e+19,0,14102100,1005,1,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0
5,1.000072e+19,0,14102100,1005,0,1,0,16920,320,50,1899,0,431,100077,117,10,21,1,0
6,1.000072e+19,0,14102100,1005,0,1,0,20362,320,50,2333,0,39,-1,157,10,21,1,0
7,1.000092e+19,0,14102100,1005,1,1,0,20632,320,50,2374,3,39,-1,23,10,21,1,0
8,1.000095e+19,1,14102100,1005,0,1,2,15707,320,50,1722,0,35,-1,79,10,21,1,0
9,1.000126e+19,0,14102100,1002,0,0,0,21689,320,50,2496,3,167,100191,23,10,21,1,0
10,1.000187e+19,0,14102100,1005,1,1,0,17747,320,50,1974,2,39,100019,33,10,21,1,0
11,1.000197e+19,0,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0
12,1.000203e+19,0,14102100,1005,0,1,2,20596,320,50,2161,0,35,100148,157,10,21,1,0
13,1.000204e+19,0,14102100,1005,0,1,0,19771,320,50,2227,0,687,100077,48,10,21,1,0
14,1.000252e+19,0,14102100,1005,0,1,0,20984,320,50,2371,0,551,-1,46,10,21,1,0
15,1.000354e+19,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,100084,79,10,21,1,0
16,1.000359e+19,0,14102100,1005,0,1,0,17914,320,50,2043,2,39,-1,32,10,21,1,0
17,1.000411e+19,0,14102100,1005,0,1,2,15708,320,50,1722,0,35,100084,79,10,21,1,0
18,1.000418e+19,0,14102100,1005,1,1,0,6558,320,50,571,2,39,-1,32,10,21,1,0
19,1.000448e+19,0,14102100,1005,0,1,0,21234,320,50,2434,3,163,100088,61,10,21,1,0
20,1.000451e+19,0,14102100,1005,0,1,0,20352,320,50,2333,0,39,-1,157,10,21,1,0
21,1.000457e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
22,1.000467e+19,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
23,1.000477e+19,1,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0
24,1.000525e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,100083,79,10,21,1,0
25,1.000533e+19,0,14102100,1010,1,4,0,21665,320,50,2493,3,35,-1,117,10,21,1,0
26,1.000554e+19,0,14102100,1005,1,1,0,20984,320,50,2371,0,551,100217,46,10,21,1,0
27,1.000561e+19,1,14102100,1005,0,1,0,21611,320,50,2480,3,297,100111,61,10,21,1,0
28,1.000565e+19,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
29,1.000595e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,7.332711e+18,0,14102100,1005,0,1,0,20596,320,50,2161,0,35,-1,157,10,21,1,0
99971,7.332961e+18,0,14102100,1005,0,1,0,15702,320,50,1722,0,35,-1,79,10,21,1,0
99972,7.332970e+18,1,14102100,1005,0,1,0,15707,320,50,1722,0,35,-1,79,10,21,1,0
99973,7.333072e+18,1,14102100,1005,0,1,0,15699,320,50,1722,0,35,-1,79,10,21,1,0
99974,7.333147e+18,0,14102100,1005,1,1,0,15703,320,50,1722,0,35,-1,79,10,21,1,0
99975,7.333147e+18,0,14102100,1005,0,1,0,17653,300,250,1994,2,39,100084,33,10,21,1,0
99976,7.333261e+18,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
99977,7.333542e+18,0,14102100,1005,0,1,3,18993,320,50,2161,0,35,-1,157,10,21,1,0
99978,7.333964e+17,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
99979,7.334135e+17,0,14102100,1005,0,1,0,21611,320,50,2480,3,297,100111,61,10,21,1,0
99980,7.334264e+18,0,14102100,1005,1,1,0,20596,320,50,2161,0,35,100130,157,10,21,1,0
99981,7.334393e+18,0,14102100,1002,0,0,0,6616,320,50,576,2,35,100131,32,10,21,1,0
99982,7.334744e+18,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,-1,79,10,21,1,0
99983,7.334746e+18,0,14102100,1005,1,1,0,20355,216,36,2333,0,39,-1,157,10,21,1,0
99984,7.334873e+18,1,14102100,1002,0,0,0,15908,320,50,1752,3,297,100081,82,10,21,1,0
99985,7.335207e+17,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,-1,79,10,21,1,0
99986,7.335435e+18,0,14102100,1005,1,1,0,16920,320,50,1899,0,431,100081,117,10,21,1,0
99987,7.335648e+18,1,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
99988,7.335695e+18,0,14102100,1005,1,1,0,17614,320,50,1993,2,1063,100083,33,10,21,1,0
99989,7.336249e+18,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,100084,79,10,21,1,0
99990,7.336318e+18,0,14102100,1005,0,1,0,9248,320,50,768,3,175,100156,42,10,21,1,0
99991,7.336369e+18,0,14102100,1005,0,1,0,15701,320,50,1722,0,35,100083,79,10,21,1,0
99992,7.336378e+18,0,14102100,1005,0,1,0,15705,320,50,1722,0,35,-1,79,10,21,1,0
99993,7.336541e+17,0,14102100,1005,1,1,2,20596,320,50,2161,0,35,100034,157,10,21,1,0
99994,7.336555e+18,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
99995,7.336716e+18,0,14102100,1005,0,1,0,21611,320,50,2480,3,297,100111,61,10,21,1,0
99996,7.337102e+18,0,14102100,1005,0,1,0,15702,320,50,1722,0,35,-1,79,10,21,1,0
99997,7.337105e+18,1,14102100,1005,0,1,0,15702,320,50,1722,0,35,-1,79,10,21,1,0
99998,7.337331e+17,0,14102100,1005,0,1,0,15708,320,50,1722,0,35,-1,79,10,21,1,0
99999,7.337345e+18,0,14102100,1002,0,0,0,21665,320,50,2493,3,35,-1,117,10,21,1,0

## ターゲット変数と特徴量を指定してsklearnに渡せるように準備する

In [113]:
target_col = 'click'
exclude_cols = ['click', 'id', 'hour']
feature_cols = [col for col in X.columns if col not in exclude_cols]

In [114]:
feature_cols

['C1',
 'banner_pos',
 'device_type',
 'device_conn_type',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'hour_month',
 'hour_day',
 'hour_weekday',
 'hour_hour']

## 説明変数（特徴量）

In [115]:
X[feature_cols].head()

,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21,hour_month,hour_day,hour_weekday,hour_hour
0,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
1,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
2,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
3,1005,0,1,0,15706,320,50,1722,0,35,100084,79,10,21,1,0
4,1005,1,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0

## 被説明変数（ターゲット変数）

In [116]:
X[target_col].head()

0    0
1    0
2    0
3    0
4    0
Name: click, dtype: int64

In [117]:
y = np.array(X[target_col])
X = np.array(X[feature_cols])

In [118]:
y

array([0, 0, 0, ..., 1, 0, 0])

In [119]:
X

array([[1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       ...,
       [1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       [1002,    0,    0, ...,   21,    1,    0]])

# モデルの作成

In [120]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [121]:
X_train, X_test, y_train, y_test = \
 train_test_split(X, y, test_size=0.3, random_state=1234)

In [122]:
X_train1, X_train2, y_train1, y_train2 = \
 train_test_split(X_train, y_train, test_size=0.3, random_state=1234)

## ランダムフォレスト

In [123]:
rf = RandomForestRegressor(random_state=1234)
rf.fit(X_train1, y_train1)
y_pred2 = rf.predict(X_train2)
rf_mse = mean_squared_error(y_train2, y_pred2)
print('Random Forest RMSE: ', np.sqrt(rf_mse))

Random Forest RMSE:  0.3685662002972477

In [124]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

17275

## 変数増加法で変数選択をしてみる

In [125]:
def get_gfs_feature_indices(X, y, features, clf):
    X_train_, X_test_, y_train_, y_test_ = \
        train_test_split(X, y, test_size=0.3, random_state=1234)
    
    #どの特徴量が何列目にあるかを辞書型で保持
    feature_indices = {feature: idx for idx, feature in enumerate(features)}
   
    # 特徴量をユニークにする
    features = set(features)
    
    # 評価（MSE）の初期化
    last_mse = np.inf
    
    #選ばれた特徴量を保存するための空集合を用意
    chosen_features = set()

    while len(chosen_features) < len(features):
        mse_features = []
        
        # 集合は引き算すると差集合
        for feature in (features - chosen_features):
            candidates = chosen_features.union(set([feature]))
            indices = [feature_indices[feature] for feature in candidates]
            clf.fit(X_train_[:, indices], y_train_)
            y_pred = clf.predict(X_test_[:, indices])
            mse = mean_squared_error(y_test_, y_pred)
            mse_features += [(mse, feature)]
        mse, feature = min(mse_features, key= lambda x:x[0])
        
        if mse >= last_mse:
            break
        last_mse = mse
        print('Newly Added Feature: {},\tRMSE Score: {}'.format(feature, np.sqrt(mse)))
        chosen_features.add(feature)
    return [feature_indices[feature] for feature in chosen_features]

In [126]:
selected_feature_index = \
get_gfs_feature_indices(X=X_train, 
                        y=y_train, 
                        features=feature_cols, 
                        clf=RandomForestRegressor(random_state=1234))

Newly Added Feature: C17,	RMSE Score: 0.3657912051594772
Newly Added Feature: banner_pos,	RMSE Score: 0.365345695516575
Newly Added Feature: device_type,	RMSE Score: 0.36506123608806695
Newly Added Feature: C19,	RMSE Score: 0.3650218194194557
Newly Added Feature: C16,	RMSE Score: 0.3649957334200158
Newly Added Feature: device_conn_type,	RMSE Score: 0.364921132185937
Newly Added Feature: C1,	RMSE Score: 0.36490012518220555
Newly Added Feature: hour_weekday,	RMSE Score: 0.36489019345904594
Newly Added Feature: hour_day,	RMSE Score: 0.3648898523429643

## 変数選択後の精度を確認

In [127]:
rf = RandomForestRegressor(random_state=1234)
rf.fit(X_train1[:, selected_feature_index], y_train1)
y_pred2 = rf.predict(X_train2[:, selected_feature_index])
rf_mse = mean_squared_error(y_train2, y_pred2)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.3648898523429643

In [128]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

17329

In [129]:
rf = RandomForestRegressor(random_state=1234)

In [130]:
params = {'n_estimators': [10, 50, 100], 'max_depth': [5, 10, 50]}

In [131]:
import sklearn 
sklearn.__version__

'0.19.1'

In [132]:
#注意: scikit-learnのバージョンが、0.18の場合は、scoring='neg_mean_squared_error'とします
gscv = GridSearchCV(rf, param_grid=params, verbose=1,
                     cv=3, scoring='neg_mean_squared_error')

In [133]:
gscv.fit(X_train1[:, selected_feature_index], y_train1)

Fitting 3 folds for each of 9 candidates, totalling 27 fits

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   17.8s finished

GridSearchCV(cv=3, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=1234, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [10, 50, 100], 'max_depth': [5, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring='neg_mean_squared_error', verbose=1)

In [134]:
gscv.best_params_

{'max_depth': 10, 'n_estimators': 100}

## パラメーターチューニング後のスコア

In [135]:
rf = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=1234)
rf.fit(X_train1[:, selected_feature_index ], y_train1)
y_pred2 = rf.predict(X_train2[:, selected_feature_index])
rf_mse = mean_squared_error(y_train2, y_pred2)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.3646438833253153

In [136]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

17332

## テストデータへ適用して精度を確認する

In [137]:
rf = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=1234)
rf.fit(X_train[:, selected_feature_index], y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=1234, verbose=0, warm_start=False)

In [138]:
y_pred_on_test = rf.predict(X_test[:, selected_feature_index])
rf_mse = mean_squared_error(y_test, y_pred_on_test)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.3643415503786495

In [139]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

17332

## submission用csvの作成

In [140]:
test_fname = 'test.csv'
reader_test = pd.read_csv(test_fname, chunksize=kensu)
df_test_origin = reader_test.get_chunk(kensu)

In [141]:
df_test = preprocess(df_test_origin)

In [142]:
selected_feature_index2 = ['C17',
'banner_pos',
'device_type',
'C19',
'C16',
'device_conn_type',
'C1',
'hour_weekday',
'hour_day']

In [143]:
submit_data =  pd.Series(rf.predict(df_test[selected_feature_index2]), name='click', index=df_test_origin['id'])
submit_data.to_csv(submit_csv_name, header=True)