- ランダムフォレスト
- データ数　train.csv1000000
- test.csv 1000000

In [144]:
kensu = 1000000
kensu_str = '1000000'
submit_csv_name = 'submit_Quantitative_variable_' + kensu_str + '.csv'

## 必要なライブラリを読み込む

In [145]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

## データ用が多いので、絞って読み込み

In [146]:
train_fname = 'train.csv'
reader = pd.read_csv(train_fname, chunksize=kensu)

In [147]:
df_train = reader.get_chunk(kensu)

In [148]:
df_train.shape

(1000000, 24)

In [149]:
df_train.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

In [150]:
df_train.columns

Index(['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

## データの欠損値、型、columnsを確認

In [151]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 24 columns):
id                  1000000 non-null float64
click               1000000 non-null int64
hour                1000000 non-null int64
C1                  1000000 non-null int64
banner_pos          1000000 non-null int64
site_id             1000000 non-null object
site_domain         1000000 non-null object
site_category       1000000 non-null object
app_id              1000000 non-null object
app_domain          1000000 non-null object
app_category        1000000 non-null object
device_id           1000000 non-null object
device_ip           1000000 non-null object
device_model        1000000 non-null object
device_type         1000000 non-null int64
device_conn_type    1000000 non-null int64
C14                 1000000 non-null int64
C15                 1000000 non-null int64
C16                 1000000 non-null int64
C17                 1000000 non-null int64
C18                 1000000 non-null int64
C19                 1000000 non-null int64
C20                 1000000 non-null int64
C21                 1000000 non-null int64
dtypes: float64(1), int64(14), object(9)
memory usage: 183.1+ MB

## Numericalデータの統計情報

In [152]:
df_train.describe()

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,1.000000e+06,1000000.000000,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,9.376314e+18,0.160219,1.410210e+07,1005.088166,0.229922,1.025540,0.223363,18262.203151,318.965808,56.495546,2041.031112,1.452262,190.779388,45505.857239,69.936118
std,5.236908e+18,0.366809,1.493256e+00,1.156928,0.464627,0.453899,0.667164,3510.366302,19.452897,36.546944,441.200965,1.362637,273.439286,49843.810147,38.513846
min,9.984920e+12,0.000000,1.410210e+07,1001.000000,0.000000,0.000000,0.000000,375.000000,120.000000,20.000000,112.000000,0.000000,33.000000,-1.000000,13.000000
25%,4.846660e+18,0.000000,1.410210e+07,1005.000000,0.000000,1.000000,0.000000,15707.000000,320.000000,50.000000,1722.000000,0.000000,35.000000,-1.000000,43.000000
50%,9.834387e+18,0.000000,1.410210e+07,1005.000000,0.000000,1.000000,0.000000,19251.000000,320.000000,50.000000,2161.000000,1.000000,39.000000,-1.000000,61.000000
75%,1.373053e+19,0.000000,1.410210e+07,1005.000000,0.000000,1.000000,0.000000,21153.000000,320.000000,50.000000,2420.000000,3.000000,297.000000,100084.000000,79.000000
max,1.844670e+19,1.000000,1.410210e+07,1012.000000,7.000000,5.000000,5.000000,21705.000000,1024.000000,1024.000000,2497.000000,3.000000,1835.000000,100248.000000,195.000000

## Categoricalデータの統計情報

In [153]:
df_train.describe(include=['O'])

,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model
count,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000
unique,2075,2030,21,2309,156,23,83431,313002,4581
top,85f751fd,c4e18dd6,50e219e0,ecad2386,7801e8d9,07d7df22,a99f214a,6b9769f2,8a4875bd
freq,332893,348412,360056,667107,707429,679869,840265,5886,59771

## hour列から　月、日、曜日、時を抜き出すために関数を用意

In [154]:
from datetime import datetime as dt
# hour列から　月、日、曜日、時を抜き出すために関数を用意

def get_month_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.month
def get_day_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.day
def get_weekday_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.weekday()
def get_hour_from_time(x):
    time_date = dt.strptime(str(x), "%y%m%d%H")
    return time_date.hour

In [155]:
def preprocess(df_train):
    
    # 上記で作成した関数をapplyで一括適用
    df_train["hour_month"] = df_train["hour"].apply(get_month_from_time)
    df_train["hour_day"] = df_train["hour"].apply(get_day_from_time)
    df_train["hour_weekday"] = df_train["hour"].apply(get_weekday_from_time)
    df_train["hour_hour"] = df_train["hour"].apply(get_hour_from_time)
   
    # カテゴリ変数からダミー変数の作成
    X = df_train.iloc[:, 0:28]
    colnames_categorical = ['site_id', 'site_domain','site_category', 'app_id', 'app_domain', 'app_category', 'device_id','device_ip', 'device_model']
#    X_dummy = pd.get_dummies(X[colnames_categorical])
#   X = pd.merge(X, X_dummy, left_index=True, right_index=True)
    X = X.drop(colnames_categorical, axis=1)
    
    
    return X

In [156]:
X = preprocess(df_train)

In [157]:
X

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21,hour_month,hour_day,hour_weekday,hour_hour
0,1.000009e+18,0,14102100,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
1,1.000017e+19,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
2,1.000037e+19,0,14102100,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
3,1.000064e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,100084,79,10,21,1,0
4,1.000068e+19,0,14102100,1005,1,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0
5,1.000072e+19,0,14102100,1005,0,1,0,16920,320,50,1899,0,431,100077,117,10,21,1,0
6,1.000072e+19,0,14102100,1005,0,1,0,20362,320,50,2333,0,39,-1,157,10,21,1,0
7,1.000092e+19,0,14102100,1005,1,1,0,20632,320,50,2374,3,39,-1,23,10,21,1,0
8,1.000095e+19,1,14102100,1005,0,1,2,15707,320,50,1722,0,35,-1,79,10,21,1,0
9,1.000126e+19,0,14102100,1002,0,0,0,21689,320,50,2496,3,167,100191,23,10,21,1,0
10,1.000187e+19,0,14102100,1005,1,1,0,17747,320,50,1974,2,39,100019,33,10,21,1,0
11,1.000197e+19,0,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0
12,1.000203e+19,0,14102100,1005,0,1,2,20596,320,50,2161,0,35,100148,157,10,21,1,0
13,1.000204e+19,0,14102100,1005,0,1,0,19771,320,50,2227,0,687,100077,48,10,21,1,0
14,1.000252e+19,0,14102100,1005,0,1,0,20984,320,50,2371,0,551,-1,46,10,21,1,0
15,1.000354e+19,0,14102100,1005,0,1,0,15699,320,50,1722,0,35,100084,79,10,21,1,0
16,1.000359e+19,0,14102100,1005,0,1,0,17914,320,50,2043,2,39,-1,32,10,21,1,0
17,1.000411e+19,0,14102100,1005,0,1,2,15708,320,50,1722,0,35,100084,79,10,21,1,0
18,1.000418e+19,0,14102100,1005,1,1,0,6558,320,50,571,2,39,-1,32,10,21,1,0
19,1.000448e+19,0,14102100,1005,0,1,0,21234,320,50,2434,3,163,100088,61,10,21,1,0
20,1.000451e+19,0,14102100,1005,0,1,0,20352,320,50,2333,0,39,-1,157,10,21,1,0
21,1.000457e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
22,1.000467e+19,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
23,1.000477e+19,1,14102100,1005,0,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,0
24,1.000525e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,100083,79,10,21,1,0
25,1.000533e+19,0,14102100,1010,1,4,0,21665,320,50,2493,3,35,-1,117,10,21,1,0
26,1.000554e+19,0,14102100,1005,1,1,0,20984,320,50,2371,0,551,100217,46,10,21,1,0
27,1.000561e+19,1,14102100,1005,0,1,0,21611,320,50,2480,3,297,100111,61,10,21,1,0
28,1.000565e+19,0,14102100,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,0
29,1.000595e+19,0,14102100,1005,0,1,0,15706,320,50,1722,0,35,-1,79,10,21,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,1.474067e+19,0,14102105,1005,0,1,0,21684,320,50,2496,3,167,100199,23,10,21,1,5
999971,1.474073e+19,0,14102105,1005,0,1,0,21660,320,50,2446,3,171,100228,156,10,21,1,5
999972,1.474073e+19,0,14102105,1005,0,1,2,21647,320,50,2487,1,547,100183,51,10,21,1,5
999973,1.474082e+19,0,14102105,1005,1,1,0,15701,320,50,1722,0,35,-1,79,10,21,1,5
999974,1.474085e+19,0,14102105,1005,0,1,0,21664,320,50,2492,3,35,-1,43,10,21,1,5
999975,1.474090e+19,0,14102105,1005,0,1,0,21654,320,50,2489,1,547,-1,51,10,21,1,5
999976,1.474095e+19,0,14102105,1005,1,1,0,19251,320,50,2201,3,35,-1,43,10,21,1,5
999977,1.474103e+19,0,14102105,1005,1,1,0,19878,320,50,2271,0,687,-1,48,10,21,1,5
999978,1.474123e+19,0,14102105,1005,0,1,0,21611,320,50,2480,3,299,100111,61,10,21,1,5
999979,1.474124e+19,0,14102105,1005,0,1,0,19251,320,50,2201,3,35,-1,43,10,21,1,5
999980,1.474124e+19,0,14102105,1005,1,1,0,20596,320,50,2161,0,35,-1,157,10,21,1,5
999981,1.474130e+19,0,14102105,1005,0,1,0,21664,320,50,2492,3,35,100076,43,10,21,1,5
999982,1.474133e+19,1,14102105,1005,0,1,0,19493,320,50,2229,0,687,100031,48,10,21,1,5
999983,1.474135e+19,0,14102105,1005,1,1,0,17262,320,50,1872,3,39,-1,23,10,21,1,5
999984,1.474136e+19,1,14102105,1005,1,1,0,16920,320,50,1899,0,431,100074,117,10,21,1,5
999985,1.474140e+19,0,14102105,1005,0,1,2,21666,320,50,2494,3,35,-1,112,10,21,1,5
999986,1.474142e+19,1,14102105,1005,0,1,2,21666,320,50,2494,3,35,-1,112,10,21,1,5
999987,1.474149e+19,0,14102105,1012,0,1,2,21611,320,50,2480,3,299,100111,61,10,21,1,5
999988,1.474158e+19,0,14102105,1005,1,1,0,16071,320,50,1784,2,175,-1,95,10,21,1,5
999989,1.474159e+19,0,14102105,1005,1,1,0,20352,320,50,2333,0,39,100081,157,10,21,1,5
999990,1.474162e+18,0,14102105,1005,1,1,0,20362,320,50,2333,0,39,100077,157,10,21,1,5
999991,1.474163e+19,0,14102105,1005,0,1,0,15701,320,50,1722,0,35,100084,79,10,21,1,5
999992,1.474163e+19,0,14102105,1005,0,1,0,15701,320,50,1722,0,35,100083,79,10,21,1,5
999993,1.474164e+19,0,14102105,1005,0,1,0,19251,320,50,2201,3,35,-1,43,10,21,1,5
999994,1.474164e+19,1,14102105,1005,0,1,0,15707,320,50,1722,0,35,-1,79,10,21,1,5
999995,1.474165e+19,0,14102105,1005,0,1,0,15699,320,50,1722,0,35,100084,79,10,21,1,5
999996,1.474170e+19,0,14102105,1012,0,1,2,21612,320,50,2481,3,297,100111,61,10,21,1,5
999997,1.474176e+17,0,14102105,1005,1,1,0,15705,320,50,1722,0,35,100083,79,10,21,1,5
999998,1.474177e+19,0,14102105,1005,0,1,0,20366,320,50,2333,0,39,-1,157,10,21,1,5
999999,1.474188e+19,0,14102105,1005,0,1,3,21681,320,50,2496,3,167,-1,23,10,21,1,5

## ターゲット変数と特徴量を指定してsklearnに渡せるように準備する

In [158]:
target_col = 'click'
exclude_cols = ['click', 'id', 'hour']
feature_cols = [col for col in X.columns if col not in exclude_cols]

In [159]:
feature_cols

['C1',
 'banner_pos',
 'device_type',
 'device_conn_type',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'hour_month',
 'hour_day',
 'hour_weekday',
 'hour_hour']

## 説明変数（特徴量）

In [160]:
X[feature_cols].head()

,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21,hour_month,hour_day,hour_weekday,hour_hour
0,1005,0,1,2,15706,320,50,1722,0,35,-1,79,10,21,1,0
1,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
2,1005,0,1,0,15704,320,50,1722,0,35,100084,79,10,21,1,0
3,1005,0,1,0,15706,320,50,1722,0,35,100084,79,10,21,1,0
4,1005,1,1,0,18993,320,50,2161,0,35,-1,157,10,21,1,0

## 被説明変数（ターゲット変数）

In [161]:
X[target_col].head()

0    0
1    0
2    0
3    0
4    0
Name: click, dtype: int64

In [162]:
y = np.array(X[target_col])
X = np.array(X[feature_cols])

In [163]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [164]:
X

array([[1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       [1005,    0,    1, ...,   21,    1,    0],
       ...,
       [1005,    1,    1, ...,   21,    1,    5],
       [1005,    0,    1, ...,   21,    1,    5],
       [1005,    0,    1, ...,   21,    1,    5]])

# モデルの作成

In [165]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [166]:
X_train, X_test, y_train, y_test = \
 train_test_split(X, y, test_size=0.3, random_state=1234)

In [167]:
X_train1, X_train2, y_train1, y_train2 = \
 train_test_split(X_train, y_train, test_size=0.3, random_state=1234)

## ランダムフォレスト

In [168]:
rf = RandomForestRegressor(random_state=1234)
rf.fit(X_train1, y_train1)
y_pred2 = rf.predict(X_train2)
rf_mse = mean_squared_error(y_train2, y_pred2)
print('Random Forest RMSE: ', np.sqrt(rf_mse))

Random Forest RMSE:  0.35263084502393416

In [169]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

176092

## 変数増加法で変数選択をしてみる

In [170]:
def get_gfs_feature_indices(X, y, features, clf):
    X_train_, X_test_, y_train_, y_test_ = \
        train_test_split(X, y, test_size=0.3, random_state=1234)
    
    #どの特徴量が何列目にあるかを辞書型で保持
    feature_indices = {feature: idx for idx, feature in enumerate(features)}
   
    # 特徴量をユニークにする
    features = set(features)
    
    # 評価（MSE）の初期化
    last_mse = np.inf
    
    #選ばれた特徴量を保存するための空集合を用意
    chosen_features = set()

    while len(chosen_features) < len(features):
        mse_features = []
        
        # 集合は引き算すると差集合
        for feature in (features - chosen_features):
            candidates = chosen_features.union(set([feature]))
            indices = [feature_indices[feature] for feature in candidates]
            clf.fit(X_train_[:, indices], y_train_)
            y_pred = clf.predict(X_test_[:, indices])
            mse = mean_squared_error(y_test_, y_pred)
            mse_features += [(mse, feature)]
        mse, feature = min(mse_features, key= lambda x:x[0])
        
        if mse >= last_mse:
            break
        last_mse = mse
        print('Newly Added Feature: {},\tRMSE Score: {}'.format(feature, np.sqrt(mse)))
        chosen_features.add(feature)
    return [feature_indices[feature] for feature in chosen_features]

In [171]:
selected_feature_index = \
get_gfs_feature_indices(X=X_train, 
                        y=y_train, 
                        features=feature_cols, 
                        clf=RandomForestRegressor(random_state=1234))

Newly Added Feature: C14,	RMSE Score: 0.3513395127162716
Newly Added Feature: banner_pos,	RMSE Score: 0.35084999929389676
Newly Added Feature: C1,	RMSE Score: 0.35049413324382167
Newly Added Feature: device_conn_type,	RMSE Score: 0.35035492388431877
Newly Added Feature: C19,	RMSE Score: 0.35032627481962014
Newly Added Feature: C15,	RMSE Score: 0.3503059609306762
Newly Added Feature: C18,	RMSE Score: 0.3502958681106884
Newly Added Feature: device_type,	RMSE Score: 0.3502911198865362

## 変数選択後の精度を確認

In [172]:
rf = RandomForestRegressor(random_state=1234)
rf.fit(X_train1[:, selected_feature_index], y_train1)
y_pred2 = rf.predict(X_train2[:, selected_feature_index])
rf_mse = mean_squared_error(y_train2, y_pred2)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.3502911198865362

In [173]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

176631

In [174]:
rf = RandomForestRegressor(random_state=1234)

In [175]:
params = {'n_estimators': [10, 50, 100], 'max_depth': [5, 10, 50]}

In [176]:
import sklearn 
sklearn.__version__

'0.19.1'

In [177]:
#注意: scikit-learnのバージョンが、0.18の場合は、scoring='neg_mean_squared_error'とします
gscv = GridSearchCV(rf, param_grid=params, verbose=1,
                     cv=3, scoring='neg_mean_squared_error')

In [178]:
gscv.fit(X_train1[:, selected_feature_index], y_train1)

Fitting 3 folds for each of 9 candidates, totalling 27 fits

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:  8.2min finished

GridSearchCV(cv=3, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=1234, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [10, 50, 100], 'max_depth': [5, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring='neg_mean_squared_error', verbose=1)

In [181]:
gscv.best_params_

{'max_depth': 10, 'n_estimators': 100}

## パラメーターチューニング後のスコア

In [182]:
rf = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=1234)
rf.fit(X_train1[:, selected_feature_index ], y_train1)
y_pred2 = rf.predict(X_train2[:, selected_feature_index])
rf_mse = mean_squared_error(y_train2, y_pred2)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.3503126039185984

In [183]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

176640

## テストデータへ適用して精度を確認する

In [184]:
rf = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=1234)
rf.fit(X_train[:, selected_feature_index], y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=1234, verbose=0, warm_start=False)

In [185]:
y_pred_on_test = rf.predict(X_test[:, selected_feature_index])
rf_mse = mean_squared_error(y_test, y_pred_on_test)
print('RandomForest RMSE: ', np.sqrt(rf_mse))

RandomForest RMSE:  0.34883966223248064

In [186]:
print(accuracy_score(y_pred2.round(), y_train2,normalize=False))

176640

## submission用csvの作成

In [187]:
test_fname = 'test.csv'
reader_test = pd.read_csv(test_fname, chunksize=kensu)
df_test_origin = reader_test.get_chunk(kensu)

In [188]:
df_test = preprocess(df_test_origin)

In [189]:
selected_feature_index2 = [
'C14',
'banner_pos',
'C1',
'device_conn_type',
'C19',
'C15',
'C18',
'device_type'
]

In [190]:
submit_data =  pd.Series(rf.predict(df_test[selected_feature_index2]), name='click', index=df_test_origin['id'])
submit_data.to_csv(submit_csv_name, header=True)